### PR TITLE
Add inclusion section to homepage.

### PR DESCRIPTION
**Pull request by rduplain**
I've updated the CMS to add the section's content. I especially made it a point to use a CMS section here, since anchor links to the FAQ are sequential and therefore fragile.

I updated an inner README for accuracy along the way.

### CODE REVIEW

**Comment by andrew-boyd** [comment]
Ha, good to know. I'd be very curious if anyone actually hit the site that way, and why.

**Comment by rduplain** [comment]
Looking around for a good introduction, so I'll go straight to an authoritative piece:
https://www.w3.org/standards/webdesign/accessibility

The idea in using `lynx` was that in a few seconds I could check text-only experiences (which could then be spoken in text-to-speech engines) from my terminal. Cursory, indeed, but I find it telling. I'm not sure how the various accessibility browsers out there would handle the JavaScript registration process on airtable, so I cannot provide a final conclusion there, but we now have a fallback to text-only mode which will certainly work.

**Comment by rduplain** [comment]
I'll defer to web [503 compliance](https://www.nod.org/resources/compliance/) experts on any further discussion.

**Comment by rduplain** [comment]
Just in case it's lost in the thread and for the record. Braid _definitely_ does accessibility work. I was just providing an explanation behind my quick review.

**Comment by andrew-boyd** [comment]
Read up on `lynx` which I was not previously familiar with. Good call @rduplain on using it as a quick check for what a screen-reader experience would be like. Hadn't occurred to me!

**Comment by rduplain** [comment]
If you are interested in this, the `links` browser has some notable differences from the `lynx` browser:
https://en.wikipedia.org/wiki/Links_(web_browser)

**Comment by rduplain** [comment]
For the logs, I learned about Chrome plugin, [aXe](https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd), from @dylansheffer. aXe-core [is part of Chrome Lighthouse](https://www.deque.com/blog/google-selects-deques-axe-chrome-devtools/).

**Pull request merged**
